
```{r}
###############################
######      Inicio        #####
###############################

data = read.csv( paste(path,"bases/construccion/","base_axes_sinRepros_final_4.csv", sep="") , header = T, sep = ',')

data[, 'filtro'] = ifelse((data$indeterminado + data$insuficiente) == 0, 0, 1)
data[, 'tm'] = data$malo
data[, 'malo'] = as.factor(data$malo)

writeClipboard(gsub("\\\\", "/", readClipboard()))

X_train_num = read.csv( paste(path,"bases/train_test/","X_train_num.csv", sep="") , header = T, sep = ',')
X_train_cat = read.csv( paste(path,"bases/train_test/","X_train_cat.csv", sep="") , header = T, sep = ',')
X_test_num = read.csv( paste(path,"bases/train_test/","X_test_num.csv", sep="") , header = T, sep = ',')
X_test_cat = read.csv( paste(path,"bases/train_test/","X_test_cat.csv", sep="") , header = T, sep = ',')
y_train = read.csv( paste(path,"bases/train_test/","y_train.csv", sep="") , header = T, sep = ',')
y_test = read.csv( paste(path,"bases/train_test/","y_test.csv", sep="") , header = T, sep = ',')
 
rownames(X_train_num) = X_train_num$X; X_train_num$X = NULL
rownames(X_train_cat) = X_train_cat$X; X_train_cat$X = NULL
rownames(X_test_num) = X_test_num$X; X_test_num$X = NULL
rownames(X_test_cat) = X_test_cat$X; X_test_cat$X = NULL
rownames(y_train) = y_train$X; y_train$X = NULL
rownames(y_test) = y_test$X; y_test$X = NULL
```

```{r}
var_num = c(
  # # # despues de filtros
  # "por_mora60_max1m12",
  # "saldo_mora60_max1m12",
  # "provision",
  # "can_emp_1m",
  # "disp_efectivo_max1m6",
  # "por_uso_efectivo_max1m6",
  # "por_uso_linea_max1m6",
  # variables de perimetro
  "edad",
  "ci",
  "pv",
  # "ci_pv", # se crea
  "cuota",
  "calificacion_max1m12",
  "saldo_max1m12",
  "mora_max1m12",
  "saldo_castigo_max1m12",
  "linea_activa_max1m12",
  "por_uso_linea_max1m12",
  "expcred_1m12",
  "frec_por_cal0_100_1m12"
  # # # modelo vigente
  # "linea_total_1m",
  # "frec_mora60_1m12",
  # # # IV mayores a 2% en train y test
  # # # ultimo mes
  # "por_uso_linea_1m",
  # "mora_1m",
  # "saldo_1m",
  # "linea_activa_1m",
  # 'por_mora_0_1m',
  # 'por_cal4_1m',
  # 'por_cal34_1m',
  # 'por_mora90_1m',
  # 'saldo_mora90_1m',
  # 'por_mora60_1m',
  # 'saldo_mora60_1m',
  # 'saldo_cal4_1m',
  # 'saldo_cal34_1m',
  # 'por_castigo_1m',
  # 'saldo_castigo_1m',
  # 'por_vig_1m',
  # 'por_mora30_1m',
  # 'saldo_mora30_1m',
  # 'por_cal234_1m',
  # 'por_cal0_1m',
  # 'saldo_cal234_1m',
  # 'por_cal1234_1m',
  # 'calificacion_1m',
  # 'saldo_cal1234_1m',
  # 'por_mora0_1m',
  # 'saldo_mora0_1m',
  # # # IV mayor a 2% en train restantes
  # # # IV mayor a 2% en test restantes
)

length(var_num)
length(unique(var_num))
```

```{r}
######  Tratamiento Categoricas #####
```

```{r}
var_cat = c(
  # Fisher
  # rescatamos demosgraficas
  "perfil",
  "estado_civil",
  "marca",
  "rec_por_cal4_100_1m12"
  # # # IV mayor a 2% en ambos
  # # # iv train mayor a 2% restantes
)

length(var_cat)
length(unique(var_cat))
```

```{r}
##################################
######      Bivariados      ######
##################################
```

```{r}
############  Variables Numericas ############
```

```{r}
data_train = cbind(X_train_num[, var_num], y_train)

data_train[, 'tm'] = data_train$malo
data_train[, 'malo'] = as.factor(data_train$malo)

data_test = cbind(X_test_num[, var_num], y_test)

data_test[, 'tm'] = data_test$malo
data_test[, 'malo'] = as.factor(data_test$malo)
 
# # transformacion
data_train[,'ci_pv'] = ifelse(is.na(data_train$pv), NA, data_train$ci/data_train$pv)
data_train[,'edad'] = as.numeric(X_train_num[,'edad'])
data_train[,'frec_mora60_1m12'] = as.numeric(X_train_num[,'frec_mora60_1m12'])
data_train[,'frec_calificacion_0_1m12'] = as.numeric(X_train_num[,'frec_calificacion_0_1m12'])
data_train[,'calificacion_max1m6'] = as.character(X_train_num[,'calificacion_max1m6'])
# data_train[,'frec_por_cal0_100_1m12'] = as.numeric(X_train_num[,'frec_por_cal0_100_1m12'])
# data_train[,'frec_mora30_1m12'] = as.numeric(X_train_num[,'frec_mora30_1m12'])
# #
data_test[,'ci_pv'] = ifelse(is.na(data_test$pv), NA, data_test$ci/data_test$pv)
data_test[,'edad'] = as.numeric(X_test_num[,'edad'])
data_test[,'frec_mora60_1m12'] = as.numeric(X_test_num[,'frec_mora60_1m12'])
data_test[,'frec_calificacion_0_1m12'] = as.numeric(X_test_num[,'frec_calificacion_0_1m12'])
data_test[,'calificacion_max1m6'] = as.character(X_test_num[,'calificacion_max1m6'])
# data_test[,'frec_por_cal0_100_1m12'] = as.numeric(X_test_num[,'frec_por_cal0_100_1m12'])
# data_test[,'frec_mora30_1m12'] = as.numeric(X_test_num[,'frec_mora30_1m12'])
 
# # imputacion
# data_train$cuota[is.na(data_train$cuota)] = median(X_train_num$cuota, na.rm = T) # 1348.865
# data_train$ci_pv[is.na(data_train$ci_pv)] = median(X_train_num$ci_pv, na.rm = T) # 0.03529931
# #
# data_test$cuota[is.na(data_test$cuota)] = 1348.865
# data_test$ci_pv[is.na(data_test$ci_pv)] = 0.03529931
```

```{r}
dim(data_train)
dim(data_test)
```

```{r}
c(var_num[1:11],"ci_pv")
biv_num = list(name = c(), iv_tr = c(), iv_ts = c())
```

```{r}
# bin = c(0.0252, 0.049718)
# tb = AnalisisWoe('ci_pv', list(data_train, data_test), 'numeric', bin) # sin sentido
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(6)# iv test bajo
# tb = AnalisisWoe('frec_calificacion_0_1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(7)
# tb = AnalisisWoe('expcred_1m12', list(data_train, data_test), 'numeric', bin) # iv test bajo
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0.83916)
tb = AnalisisWoe('por_uso_linea_max1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1000)
tb = AnalisisWoe('linea_activa_max1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0)
# tb = AnalisisWoe('saldo_castigo_max1m12', list(data_train, data_test), 'numeric', bin) # iv test bajo
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # iv test bajo
# tb = AnalisisWoe('mora_max1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(2637.0805)
# tb = AnalisisWoe('saldo_max1m12', list(data_train, data_test), 'numeric', bin) # sin sentido
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# A=c("0")
# B=c("8","9")
# C=c("1","2","3","4")
# tb = AnalisisWoe('calificacion_max1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(1161.95)
# tb = AnalisisWoe('cuota', list(data_train, data_test), 'numeric', bin) # sin sentido
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(499)
tb = AnalisisWoe('ci', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(26, 35, 40, 45)
tb = AnalisisWoe('edad', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
############  Variables Categoricas ############
```

```{r}
var_cat = c(var_cat)

data_train = cbind(X_train_cat[, var_cat], y_train)

data_train[, 'tm'] = data_train$malo
data_train[, 'malo'] = as.factor(data_train$malo)

data_test = cbind(X_test_cat[, var_cat], y_test)

data_test[, 'tm'] = data_test$malo
data_test[, 'malo'] = as.factor(data_test$malo)
```

```{r}
dim(data_train)
dim(data_test)
```

```{r}
var_cat
biv_cat = list(name = c(), iv_tr = c(), iv_ts = c())
```

```{r}
# A=c("1.0","2.0")
# D=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0","Otros")
# tb = AnalisisWoe('rec_por_cal4_100_1m12', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c('KIA','GREAT WALL','HYUNDAI','PEUGEOT','TOYOTA','NISSAN','RENAULT')
# B=c('', 'DFSK','CHEVROLET','DFSK MULTIPROPOSITO','BYD','CITROEN','FORD','HONDA','SUBARU')
# C=c('VOLVO','MAHINDRA','HAVAL','FOTON','GEELY','JAC','HAIMA','SUZUKI','INTERNATIONAL','FAW','ZOTYE','BAIC YINXIANG','MAZDA','CHERY','MITSUBISHI','BAIC','BRILLIANCE','FIAT','MG','SHINERAY','DONGFENG','CHANGAN','JINBEI','JIMBEI','SWM','SOUEAST','LIFAN','JMC','SSANG YONG','VOLKSWAGEN')
# tb = AnalisisWoe('marca', list(data_train, data_test), 'factor', list(A,B,C))# sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # IV test bajo
# tb = AnalisisWoe('estado_civil', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("5.Propietario")
tb = AnalisisWoe('perfil', list(data_train, data_test), 'factor', NULL)
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
length(biv_num$name)
length(biv_cat$name)
```
