
```{r}
###############################
######      Inicio        #####
###############################

data = read.csv( paste(path,"bases/construccion/","base_axes_sinRepros_final_3.csv", sep="") , header = T, sep = ',')

data[, 'filtro'] = ifelse((data$indeterminado + data$insuficiente) == 0, 0, 1)
data[, 'tm'] = data$malo
data[, 'malo'] = as.factor(data$malo)

writeClipboard(gsub("\\\\", "/", readClipboard()))

X_train_num = read.csv( paste(path,"bases/train_test/","X_train_num.csv", sep="") , header = T, sep = ',')
X_train_cat = read.csv( paste(path,"bases/train_test/","X_train_cat.csv", sep="") , header = T, sep = ',')
X_test_num = read.csv( paste(path,"bases/train_test/","X_test_num.csv", sep="") , header = T, sep = ',')
X_test_cat = read.csv( paste(path,"bases/train_test/","X_test_cat.csv", sep="") , header = T, sep = ',')
y_train = read.csv( paste(path,"bases/train_test/","y_train.csv", sep="") , header = T, sep = ',')
y_test = read.csv( paste(path,"bases/train_test/","y_test.csv", sep="") , header = T, sep = ',')
 
rownames(X_train_num) = X_train_num$X; X_train_num$X = NULL
rownames(X_train_cat) = X_train_cat$X; X_train_cat$X = NULL
rownames(X_test_num) = X_test_num$X; X_test_num$X = NULL
rownames(X_test_cat) = X_test_cat$X; X_test_cat$X = NULL
rownames(y_train) = y_train$X; y_train$X = NULL
rownames(y_test) = y_test$X; y_test$X = NULL
```

```{r}
var_num = c(
  # despues de filtros
  "ci",
  "cuota",
  "pv",
  "saldo_cal4_max1m6",
  "por_cal34_max1m3",
  "can_emp_1m",
  "edad",
  "saldo_cal1234_max1m3",
  "disp_efectivo_max1m6",
  "por_uso_efectivo_max1m6",
  "por_uso_linea_max1m6",
  # modelo vigente
  "linea_total_1m",
  "frec_mora60_1m12",
  # IV mayores a 2% en train y test
  'frec_calificacion_0_1m12',
  'por_mora_0_min1m6',
  'por_mora_0_min1m3',
  'por_vig_min1m3',
  'por_vig_min1m6',
  'por_vig_min1m12',
  'por_mora_0_min1m12',
  'calificacion_max1m6',
  'linea_usada_max1m6',
  'linea_total_max1m6',
  'disp_efectivo_max1m12',
  'por_uso_efectivo_max1m12',
  'linea_activa_max1m6',
  'linea_total_max1m12',
  'linea_activa_max1m12',
  'por_cal0_min1m12'
  # # ultimo mes
  # "por_uso_linea_1m",
  # "mora_1m",
  # "saldo_1m",
  # "linea_activa_1m",
  # 'por_mora_0_1m',
  # 'por_cal4_1m',
  # 'por_cal34_1m',
  # 'por_mora90_1m',
  # 'saldo_mora90_1m',
  # 'por_mora60_1m',
  # 'saldo_mora60_1m',
  # 'saldo_cal4_1m',
  # 'saldo_cal34_1m',
  # 'por_castigo_1m',
  # 'saldo_castigo_1m',
  # 'por_vig_1m',
  # 'por_mora30_1m',
  # 'saldo_mora30_1m',
  # 'por_cal234_1m',
  # 'por_cal0_1m',
  # 'saldo_cal234_1m',
  # 'por_cal1234_1m',
  # 'calificacion_1m',
  # 'saldo_cal1234_1m',
  # 'por_mora0_1m',
  # 'saldo_mora0_1m',
  # # IV mayor a 2% en train restantes
  # 'saldo_cal34_max1m3',
  # 'por_mora90_max1m3',
  # 'saldo_mora90_max1m3',
  # 'por_mora60_max1m3',
  # 'saldo_mora60_max1m3',
  # 'por_cal4_max1m6',
  # 'por_mora90_max1m6',
  # 'saldo_mora90_max1m6',
  # 'por_mora60_max1m6',
  # 'saldo_mora60_max1m6',
  # 'por_cal4_max1m3',
  # 'frec_por_cal0_100_1m12',
  # 'saldo_cal4_max1m3',
  # 'por_mora60_max1m12',
  # 'saldo_mora60_max1m12',
  # 'calificacion_max1m12',
  # 'por_mora90_max1m12',
  # 'saldo_mora90_max1m12',
  # 'por_castigo_max1m6',
  # 'saldo_castigo_max1m6',
  # 'por_cal0_min1m3',
  # 'saldo_cal34_max1m6',
  # 'por_cal4_max1m12',
  # 'por_castigo_max1m3',
  # 'saldo_castigo_max1m3',
  # 'saldo_cal4_max1m12',
  # 'por_cal34_max1m12',
  # 'por_cal34_max1m6',
  # 'saldo_cal34_max1m12',
  # 'frec_mora_0_1m12',
  # 'calificacion_max1m3',
  # 'por_cal234_max1m3',
  # 'saldo_cal234_max1m3',
  # 'por_mora30_max1m3',
  # 'saldo_mora30_max1m3',
  # 'por_cal0_min1m6',
  # 'frec_por_cal4_100_1m12',
  # 'por_castigo_max1m12',
  # 'saldo_castigo_max1m12',
  # 'por_mora30_max1m6',
  # 'saldo_mora30_max1m6',
  # 'por_cal1234_max1m3',
  # 'frec_calificacion_4_1m12',
  # 'saldo_cal234_max1m6',
  # 'frec_mora90_1m12',
  # 'frec_mora120_1m12',
  # 'por_cal234_max1m6',
  # 'frec_calificacion_34_1m12',
  # 'por_mora30_max1m12',
  # 'saldo_mora30_max1m12',
  # 'frec_mora30_1m12',
  # 'mora_max1m3',
  # 'por_mora0_max1m3',
  # 'saldo_mora0_max1m3',
  # 'frec_calificacion_1234_1m12',
  # 'por_cal234_max1m12',
  # 'frec_mora0_1m12',
  # 'saldo_cal234_max1m12',
  # 'frec_calificacion_234_1m12',
  # 'linea_usada_max1m12',
  # 'por_uso_linea_max1m12',
  # 'saldo_cal1234_max1m6',
  # 'cv_saldo_1m12',
  # 'por_cal1234_max1m6'
  # # IV mayor a 2% en test restantes
)

length(var_num)
length(unique(var_num))
```

```{r}
######  Tratamiento Categoricas #####
```

```{r}
var_cat = c(
  # Fisher
  # rescatamos demosgraficas
  "marca",
  "perfil",
  "estado_civil",
  # IV mayor a 2% en ambos
  'calificacion_var1m12',
  'calificacion_max1m6_max7m12',
  'calificacion_var1m6',
  'calificacion_max1m3_max4m12',
  'calificacion_var1m3',
  'calificacion_1m_max2m12',
  'rec_por_cal4_100_1m12',
  'por_vig_var1m6',
  'rec_calificacion_0_1m12',
  'saldo_var1m3',
  'mora_1m_max2m12',
  'por_mora_0_min1m6_min7m12',
  'rec_mora120_1m12',
  'rec_calificacion_1234_1m12',
  'rec_calificacion_34_1m12',
  'rec_mora90_1m12',
  'rec_calificacion_4_1m12',
  'rec_mora60_1m12',
  'rec_calificacion_234_1m12',
  'disp_efectivo_1m_flg',
  'linea_total_1m_flg',
  'linea_usada_1m_flg',
  'por_mora60_1m_max2m12',
  'por_mora60_var1m3',
  'linea_activa_1m_flg',
  'por_cal4_var1m6',
  'por_castigo_var1m6',
  'rec_por_cal0_100_1m12',
  'rec_mora_0_1m12',
  'por_cal4_var1m3',
  'por_mora30_var1m3',
  'por_cal34_1m_max2m12',
  'rec_mora0_1m12',
  'por_castigo_var1m3',
  'saldo_var1m6',
  'disp_efectivo_max1m3_flg',
  'linea_total_max1m3_flg',
  'linea_usada_max1m3_flg',
  'por_uso_linea_var1m6',
  'linea_activa_var1m3',
  'disp_efectivo_max1m6_flg',
  'linea_total_max1m6_flg',
  'linea_usada_max1m6_flg',
  'mora_var1m3',
  'por_cal0_min1m6_min7m12',
  'por_uso_linea_var1m3',
  'linea_activa_1m_max2m12',
  'linea_activa_var1m12',
  'linea_activa_max1m3_flg',
  'por_uso_linea_1m_max2m12',
  'linea_activa_var1m6',
  'linea_activa_max1m6_flg',
  'por_uso_linea_max1m6_max7m12',
  'linea_activa_max1m6_max7m12',
  'por_uso_linea_max1m3_max4m12',
  'por_uso_efectivo_var1m3',
  'por_uso_efectivo_1m_max2m12'
  # # iv train mayor a 2% restantes
  # 'por_cal0_var1m3',
  # 'por_mora_0_var1m12',
  # 'por_mora_0_var1m3',
  # 'por_vig_min1m6_min7m12',
  # 'por_cal0_var1m12',
  # 'por_vig_var1m12',
  # 'por_vig_var1m3',
  # 'por_vig_min1m3_min4m12',
  # 'por_mora_0_var1m6',
  # 'por_mora30_var1m12',
  # 'por_cal0_var1m6',
  # 'por_cal34_var1m12',
  # 'por_cal0_1m_min2m12',
  # 'por_mora30_max1m3_max4m12',
  # 'por_mora60_var1m12',
  # 'por_mora0_var1m12',
  # 'por_mora90_var1m12',
  # 'por_mora90_1m_max2m12',
  # 'por_mora90_max1m3_max4m12',
  # 'mora_max1m3_max4m12',
  # 'por_mora60_max1m3_max4m12',
  # 'por_mora30_var1m6',
  # 'por_cal4_1m_max2m12',
  # 'por_mora90_var1m6',
  # 'por_castigo_max1m6_max7m12',
  # 'por_cal34_var1m3',
  # 'por_cal1234_max1m3_max4m12',
  # 'saldo_max1m3_max4m12',
  # 'por_cal34_max1m3_max4m12',
  # 'por_mora_0_min1m3_min4m12',
  # 'por_mora60_var1m6',
  # 'por_mora90_max1m6_max7m12',
  # 'por_cal4_max1m3_max4m12',
  # 'por_mora90_var1m3',
  # 'por_vig_1m_min2m12',
  # 'por_cal4_max1m6_max7m12',
  # 'por_mora0_max1m6_max7m12',
  # 'por_cal0_min1m3_min4m12',
  # 'rec_mora30_1m12',
  # 'por_mora60_max1m6_max7m12',
  # 'por_castigo_1m_max2m12',
  # 'por_cal234_var1m3',
  # 'por_cal1234_var1m3',
  # 'por_castigo_max1m3_max4m12',
  # 'por_cal4_var1m12',
  # 'por_cal34_var1m6',
  # 'por_castigo_var1m12',
  # 'por_cal234_max1m3_max4m12',
  # 'por_cal234_var1m12',
  # 'saldo_max1m6_max7m12',
  # 'por_mora0_var1m3',
  # 'por_cal34_max1m6_max7m12',
  # 'saldo_1m_max2m12',
  # 'por_mora0_var1m6',
  # 'por_cal234_1m_max2m12',
  # 'por_cal234_var1m6',
  # 'por_mora0_1m_max2m12',
  # 'por_mora0_max1m3_max4m12',
  # 'por_uso_efectivo_var1m6',
  # 'por_cal1234_var1m12',
  # 'por_cal1234_1m_max2m12',
  # 'por_mora_0_1m_min2m12',
  # 'por_mora30_max1m6_max7m12',
  # 'por_uso_efectivo_var1m12',
  # 'por_cal1234_var1m6',
  # 'por_uso_efectivo_max1m6_max7m12',
  # 'por_cal1234_max1m6_max7m12',
  # 'linea_activa_max1m3_max4m12',
  # 'disp_efectivo_max1m12_flg',
  # 'linea_total_max1m12_flg',
  # 'linea_usada_max1m12_flg',
  # 'mora_var1m12',
  # 'por_cal234_max1m6_max7m12',
  # 'linea_activa_max1m12_flg',
  # 'por_uso_efectivo_max1m3_max4m12',
  # 'saldo_var1m12',
  # 'mora_var1m6',
  # 'mora_max1m6_max7m12',
  # # iv test mayor a 2% restantes
  # 'por_me_1m_max2m12',
  # 'por_me_max1m3_max4m12',
  # 'por_me_max1m6_max7m12',
  # 'por_me_var1m6',
  # 'por_me_var1m3',
  # 'por_uso_linea_var1m12',
  # 'por_novig_var1m12'
)


length(var_cat)
length(unique(var_cat))
```

```{r}
##################################
######      Bivariados      ######
##################################
```

```{r}
############  Variables Numericas ############
```

```{r}
data_train = cbind(X_train_num[, var_num], y_train)

data_train[, 'tm'] = data_train$malo
data_train[, 'malo'] = as.factor(data_train$malo)

data_test = cbind(X_test_num[, var_num], y_test)

data_test[, 'tm'] = data_test$malo
data_test[, 'malo'] = as.factor(data_test$malo)
 
# # transformacion
data_train[,'ci_pv'] = ifelse(is.na(data_train$pv), NA, data_train$ci/data_train$pv)
data_train[,'edad'] = as.numeric(X_train_num[,'edad'])
data_train[,'frec_mora60_1m12'] = as.numeric(X_train_num[,'frec_mora60_1m12'])
data_train[,'frec_calificacion_0_1m12'] = as.numeric(X_train_num[,'frec_calificacion_0_1m12'])
data_train[,'calificacion_max1m6'] = as.character(X_train_num[,'calificacion_max1m6'])
# data_train[,'frec_por_cal0_100_1m12'] = as.numeric(X_train_num[,'frec_por_cal0_100_1m12'])
# data_train[,'frec_mora30_1m12'] = as.numeric(X_train_num[,'frec_mora30_1m12'])
# #
data_test[,'ci_pv'] = ifelse(is.na(data_test$pv), NA, data_test$ci/data_test$pv)
data_test[,'edad'] = as.numeric(X_test_num[,'edad'])
data_test[,'frec_mora60_1m12'] = as.numeric(X_test_num[,'frec_mora60_1m12'])
data_test[,'frec_calificacion_0_1m12'] = as.numeric(X_test_num[,'frec_calificacion_0_1m12'])
data_test[,'calificacion_max1m6'] = as.character(X_test_num[,'calificacion_max1m6'])
# data_test[,'frec_por_cal0_100_1m12'] = as.numeric(X_test_num[,'frec_por_cal0_100_1m12'])
# data_test[,'frec_mora30_1m12'] = as.numeric(X_test_num[,'frec_mora30_1m12'])
 
# # imputacion
# data_train$cuota[is.na(data_train$cuota)] = median(X_train_num$cuota, na.rm = T) # 1348.865
# data_train$ci_pv[is.na(data_train$ci_pv)] = median(X_train_num$ci_pv, na.rm = T) # 0.03529931
# #
# data_test$cuota[is.na(data_test$cuota)] = 1348.865
# data_test$ci_pv[is.na(data_test$ci_pv)] = 0.03529931
```

```{r}
dim(data_train)
dim(data_test)
```

```{r}
c(var_num[1:27],"ci_pv")
biv_num = list(name = c(), iv_tr = c(), iv_ts = c())
```

```{r}
# bin = c(0.04,0.05) # iv test bajo
# tb = AnalisisWoe('ci_pv', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0,50,99) # iv test bajo
# tb = AnalisisWoe('por_cal0_min1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1400,3000)
tb = AnalisisWoe('linea_activa_max1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1000)
tb = AnalisisWoe('linea_total_max1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1300)
tb = AnalisisWoe('linea_activa_max1m6', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # sin sentido
# tb = AnalisisWoe('por_uso_efectivo_max1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # sin sentido
# tb = AnalisisWoe('disp_efectivo_max1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1000, 2600)
tb = AnalisisWoe('linea_total_max1m6', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(564) # Sin sentido
# tb = AnalisisWoe('linea_usada_max1m6', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
A=c("0")
B=c("8","9")
C=c("1","2","3","4")
tb = AnalisisWoe('calificacion_max1m6', list(data_train, data_test), 'factor', list(A,B,C))
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_mora_0_min1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_vig_min1m12', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_vig_min1m6', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_vig_min1m3', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_mora_0_min1m3', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(0)
tb = AnalisisWoe('por_mora_0_min1m6', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0)# iv test bajo
# tb = AnalisisWoe('frec_calificacion_0_1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0:4)# iv test bajo
# tb = AnalisisWoe('frec_mora60_1m12', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(1306.712)
tb = AnalisisWoe('linea_total_1m', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0.576675) # sin sentido logico
# tb = AnalisisWoe('por_uso_linea_max1m6', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # sin sentido logico
# tb = AnalisisWoe('por_uso_efectivo_max1m6', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # sin sentido logico
# tb = AnalisisWoe('disp_efectivo_max1m6', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0) # iv test bajo
# tb = AnalisisWoe('saldo_cal1234_max1m3', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(34, 40, 46, 56)
tb = AnalisisWoe('edad', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(1,2) # sin sentido logico
# tb = AnalisisWoe('can_emp_1m', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0, 99) # iv test bajo
# tb = AnalisisWoe('por_cal34_max1m3', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(0, 700.484, 2009.6495) # iv test bajo
# tb = AnalisisWoe('saldo_cal4_max1m6', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c(36000) # sin sentido
# tb = AnalisisWoe('pv', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
# bin = c( 1000, 1283.85, 1381) # iv test bajo
# tb = AnalisisWoe('cuota', list(data_train, data_test), 'numeric', bin)
# tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
bin = c(499)
tb = AnalisisWoe('ci', list(data_train, data_test), 'numeric', bin)
tb; biv_num = biv_iv(biv_num,tb)
```

```{r}
############  Variables Categoricas ############
```

```{r}
var_cat = c(var_cat)

data_train = cbind(X_train_cat[, var_cat], y_train)

data_train[, 'tm'] = data_train$malo
data_train[, 'malo'] = as.factor(data_train$malo)

data_test = cbind(X_test_cat[, var_cat], y_test)

data_test[, 'tm'] = data_test$malo
data_test[, 'malo'] = as.factor(data_test$malo)
```

```{r}
dim(data_train)
dim(data_test)
```

```{r}
var_cat[31:60]
biv_cat = list(name = c(), iv_tr = c(), iv_ts = c())
```

```{r}
# A=c("Cero por_uso_efectivo")
# B=c("Menor por_uso_efectivo","Igual por_uso_efectivo","Mayor por_uso_efectivo","Cien por_uso_efectivo")
# tb = AnalisisWoe('por_uso_efectivo_1m_max2m12', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa","Menor linea_activa")
# B=c("Igual linea_activa","Mayor linea_activa")
# tb = AnalisisWoe('por_uso_efectivo_var1m3', list(data_train, data_test), 'factor', NULL) # sin materialidad
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa","Menor linea_activa")
# B=c("Igual linea_activa","Mayor linea_activa")
# tb = AnalisisWoe('por_uso_linea_max1m3_max4m12', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa","Menor linea_activa")
# B=c("Igual linea_activa","Mayor linea_activa")
# tb = AnalisisWoe('linea_activa_max1m6_max7m12', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa")
# tb = AnalisisWoe('por_uso_linea_max1m6_max7m12', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero linea_activa")
tb = AnalisisWoe('linea_activa_max1m6_flg', list(data_train, data_test), 'factor', NULL) # ivs bajos
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero linea_activa")
B=c("Igual linea_activa","Mayor linea_activa","Menor linea_activa")
tb = AnalisisWoe('linea_activa_var1m6', list(data_train, data_test), 'factor', list(A,B)) # ivs bajos
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_uso_linea","Menor por_uso_linea")
# B=c("Igual por_uso_linea","Mayor por_uso_linea","Cien por_uso_linea")
# tb = AnalisisWoe('por_uso_linea_1m_max2m12', list(data_train, data_test), 'factor', list(A,B)) # ivs bajos
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero linea_activa")
tb = AnalisisWoe('linea_activa_max1m3_flg', list(data_train, data_test), 'factor', NULL)
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa")
# B=c("Menor linea_activa","Igual linea_activa","Mayor linea_activa")
# C=c("Cien por_cal0")
# tb = AnalisisWoe('linea_activa_var1m12', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa")
# B=c("Menor linea_activa","Igual linea_activa","Mayor linea_activa")
# C=c("Cien por_cal0")
# tb = AnalisisWoe('linea_activa_1m_max2m12', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_cal0","Menor por_cal0","Mayor por_cal0")
# B=c("Menor mora","Igual mora","Mayor mora")
# C=c("Cien por_cal0")
# tb = AnalisisWoe('por_uso_linea_var1m3', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero por_cal0","Menor por_cal0","Mayor por_cal0")
B=c("Menor mora","Igual mora","Mayor mora")
C=c("Cien por_cal0")
tb = AnalisisWoe('por_cal0_min1m6_min7m12', list(data_train, data_test), 'factor', list(A,C)) # ivs bajos
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero mora")
# B=c("Menor mora","Igual mora","Mayor mora")
# tb = AnalisisWoe('mora_var1m3', list(data_train, data_test), 'factor', list(A,B)) # ivs bajos
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa","Menor linea_activa")
# tb = AnalisisWoe('linea_usada_max1m6_flg', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero linea_activa","Menor linea_activa")
tb = AnalisisWoe('linea_total_max1m6_flg', list(data_train, data_test), 'factor', NULL)
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero linea_activa","Menor linea_activa")
# tb = AnalisisWoe('disp_efectivo_max1m6_flg', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero linea_activa","Menor linea_activa")
B=c("Igual linea_activa","Mayor linea_activa")
tb = AnalisisWoe('linea_activa_var1m3', list(data_train, data_test), 'factor', list(A,B))
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero saldo","Menor saldo")
# tb = AnalisisWoe('por_uso_linea_var1m6', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero saldo","Menor saldo")
# tb = AnalisisWoe('linea_usada_max1m3_flg', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero saldo","Menor saldo")
tb = AnalisisWoe('linea_total_max1m3_flg', list(data_train, data_test), 'factor', NULL)
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero saldo","Menor saldo")
# tb = AnalisisWoe('disp_efectivo_max1m3_flg', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero saldo","Menor saldo")
# B=c("Igual saldo","Mayor saldo")
# C=c("Mayor por_mora60")
# D=c("Cien por_castigo")
# tb = AnalisisWoe('saldo_var1m6', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_castigo","Menor por_castigo","Igual por_castigo","Mayor por_castigo")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_castigo")
# tb = AnalisisWoe('por_castigo_var1m3', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0")
# C=c("7.0","8.0","9.0","10.0","11.0","12.0")
# D=c("Otros")
# tb = AnalisisWoe('rec_mora_0_1m12', list(data_train, data_test), 'factor', list(A,B,C,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_cal34","Menor por_cal34","Igual por_cal34","Mayor por_cal34")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_cal34")
# tb = AnalisisWoe('por_cal34_1m_max2m12', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_mora30","Menor por_mora30","Igual por_mora30","Mayor por_mora30")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_mora30")
# tb = AnalisisWoe('por_mora30_var1m3', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_cal4","Menor por_cal4","Igual por_cal4","Mayor por_cal4")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_cal4")
# tb = AnalisisWoe('por_cal4_var1m3', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_mora_0_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0","3.0","4.0")
# B=c("5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_por_cal0_100_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_castigo","Menor por_castigo","Igual por_castigo","Mayor por_castigo")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_castigo")
# tb = AnalisisWoe('por_castigo_var1m6', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_cal4","Menor por_cal4","Igual por_cal4","Mayor por_cal4")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_cal4")
# tb = AnalisisWoe('por_cal4_var1m6', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero por_mora60","Menor por_mora60","Igual por_mora60","Mayor por_mora60")
tb = AnalisisWoe('linea_activa_1m_flg', list(data_train, data_test), 'factor', NULL) # iv test bajo
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_mora60","Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_mora60")
# tb = AnalisisWoe('por_mora60_var1m3', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_mora60","Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# B=c("Menor por_mora60","Igual por_mora60","Mayor por_mora60")
# C=c("Mayor por_mora60")
# D=c("Cien por_mora60")
# tb = AnalisisWoe('por_mora60_1m_max2m12', list(data_train, data_test), 'factor', list(A,D)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# tb = AnalisisWoe('linea_usada_1m_flg', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("1.0","2.0")
tb = AnalisisWoe('linea_total_1m_flg', list(data_train, data_test), 'factor', NULL) # sin sentido
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# tb = AnalisisWoe('disp_efectivo_1m_flg', list(data_train, data_test), 'factor', NULL) # sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_calificacion_234_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_mora60_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_calificacion_4_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0")
# B=c("3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_mora90_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0","3.0")
# B=c("4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_calificacion_34_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0")
# B=c("2.0","3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_calificacion_1234_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0")
# B=c("2.0","3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_mora120_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("Cero por_mora_0","Menor por_mora_0","Igual por_mora_0")
B=c("Menor por_mora_0","Igual por_mora_0")
C=c("Mayor por_mora_0")
D=c("Cien por_mora_0")
tb = AnalisisWoe('por_mora_0_min1m6_min7m12', list(data_train, data_test), 'factor', list(A,C,D))
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero mora","Menor mora","Igual mora")
# B=c("Igual mora")
# C=c("Mayor mora")
# D=c("Cien mora")
# tb = AnalisisWoe('mora_1m_max2m12', list(data_train, data_test), 'factor', list(A,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero saldo","Menor saldo")
# B=c("Mayor saldo","Igual saldo")
# C=c("Mayor saldo")
# D=c("Cien saldo")
# tb = AnalisisWoe('saldo_var1m3', list(data_train, data_test), 'factor', list(A,B)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0","2.0","3.0")
# B=c("4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_calificacion_0_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_vig","Mayor por_vig","Menor por_vig","Igual por_vig")
# B=c("Mayor por_vig","Menor por_vig","Igual por_vig")
# C=c("Cien por_vig")
# tb = AnalisisWoe('por_vig_var1m6', list(data_train, data_test), 'factor', list(A,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("Cero por_vig","Mayor por_vig","Menor por_vig","Igual por_vig")
# B=c("Mayor por_vig","Menor por_vig","Igual por_vig")
# C=c("Cien por_vig")
# tb = AnalisisWoe('por_vig_var1m6', list(data_train, data_test), 'factor', list(A,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("1.0")
# B=c("2.0","3.0","4.0","5.0","6.0","7.0","8.0","9.0","10.0","11.0","12.0")
# C=c("Otros")
# tb = AnalisisWoe('rec_por_cal4_100_1m12', list(data_train, data_test), 'factor', list(A,B,C)) # iv test bajo
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_1m_max2m12', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_var1m3', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_max1m3_max4m12', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_var1m6', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_max1m6_max7m12', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # sin sentido
# tb = AnalisisWoe('calificacion_var1m12', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c("5.Propietario") # IV test bajo
# tb = AnalisisWoe('estado_civil', list(data_train, data_test), 'factor', NULL)
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
A=c("5.Propietario")
tb = AnalisisWoe('perfil', list(data_train, data_test), 'factor', list(A))# sin sentido
tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
# A=c('KIA','GREAT WALL','HYUNDAI','PEUGEOT','TOYOTA','NISSAN','RENAULT')
# B=c('', 'DFSK','CHEVROLET','DFSK MULTIPROPOSITO','BYD','CITROEN','FORD','HONDA','SUBARU')
# C=c('VOLVO','MAHINDRA','HAVAL','FOTON','GEELY','JAC','HAIMA','SUZUKI','INTERNATIONAL','FAW','ZOTYE','BAIC YINXIANG','MAZDA','CHERY','MITSUBISHI','BAIC','BRILLIANCE','FIAT','MG','SHINERAY','DONGFENG','CHANGAN','JINBEI','JIMBEI','SWM','SOUEAST','LIFAN','JMC','SSANG YONG','VOLKSWAGEN')
# tb = AnalisisWoe('marca', list(data_train, data_test), 'factor', list(A,B,C))# sin sentido
# tb; biv_cat = biv_iv(biv_cat,tb)
```

```{r}
length(biv_num$name)
length(biv_cat$name)
```
